on:
  pull_request:
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    env: 
      ENVIRONMENT: ${{ github.head_ref }}
   


    steps:
    - name: Dump GitHub context
      #env:
       # GITHUB_CONTEXT: ${{ toJson(github) }}
      run: | 
        echo $ENVIRONMENT

    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: | 
        echo $ENVIRONMENT


  AKS-Deployment:
      runs-on: ubuntu-latest
      steps: 
        - name: test get env
          run: |
            echo $ENVIRONMENT
            echo "${{ github.base_ref }}"
