on:
  push:
    branches:
      - dev
      - sit 



jobs:
  Testing:
    runs-on: ubuntu-latest
    env: 
      ENVIRONMENT: ${{ github.ref_name }}

    steps:
    - name: Dump GitHub context
      #env:
       # GITHUB_CONTEXT: ${{ toJson(github) }}
      run: | 
        echo $ENVIRONMENT

    - name: Dump GitHub context
      run: | 
        echo $ENVIRONMENT


  AKS-Deployment:
      runs-on: ubuntu-latest
      env: 
        ENVIRONMENT: ${{ github.ref_name }}
   
      steps: 
        - name: test get env
          run: |
            echo $ENVIRONMENT
